kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build main
  when:
    branch:
    - main
  commands:
  - cd /mnt/website-dev
  - yarn
  - yarn build
- name: build mint
  when:
    branch:
    - mint
  commands:
  - cd /mnt/website-mint
  - yarn
  - yarn build
